-- =============================================================================
-- 038: Phase 4 seeds — future appointments, measure net_revenue, uncontrolled
-- thresholds, chronic-monitoring protocol. Deterministic (no random()).
-- =============================================================================

-- ─── Synthetic future appointments (enables AMP-1 pre-visit) ─────────────────
-- ~250 problem-list patients get a Scheduled visit 1..21 days out, with their PCP.
INSERT INTO phm_edw.appointment
  (patient_id, provider_id, appointment_date, start_time, end_time, appointment_type, status)
SELECT
  c.patient_id,
  c.pcp_provider_id,
  CURRENT_DATE + (((c.rn % 21) + 1) || ' days')::interval,
  TIME '09:00',
  TIME '09:20',
  'office_visit',
  'Scheduled'
FROM (
  SELECT p.patient_id, p.pcp_provider_id,
         row_number() OVER (ORDER BY p.patient_id) AS rn
  FROM phm_edw.patient p
  WHERE p.active_ind = 'Y' AND p.pcp_provider_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM phm_edw.problem_list pl
      WHERE pl.patient_id = p.patient_id AND pl.active_ind = 'Y' AND pl.problem_status = 'Active'
    )
  ORDER BY p.patient_id
  LIMIT 250
) c;

-- ─── Per-gap net revenue (compendium gap pricing) ────────────────────────────
UPDATE phm_edw.measure_definition SET net_revenue = 406.10 WHERE measure_code = 'CMS130v12'; -- colorectal screening
UPDATE phm_edw.measure_definition SET net_revenue = 140.00 WHERE measure_code = 'CMS125v12'; -- breast / mammogram
UPDATE phm_edw.measure_definition SET net_revenue = 50.00  WHERE measure_code = 'CMS124v12'; -- cervical
UPDATE phm_edw.measure_definition SET net_revenue = 11.18  WHERE measure_code = 'CMS122v12'; -- diabetes A1c
UPDATE phm_edw.measure_definition SET net_revenue = 250.88 WHERE measure_code IN ('CMS117v12', 'CMS147v13'); -- immunization / flu
UPDATE phm_edw.measure_definition SET net_revenue = 15.00  WHERE measure_code = 'CMS134v12'; -- diabetic nephropathy / microalbumin
UPDATE phm_edw.measure_definition SET net_revenue = 20.00  WHERE measure_code = 'CMS347v7';  -- statin / lipid
UPDATE phm_edw.measure_definition SET net_revenue = 75.00  WHERE measure_code = 'CMS131v12'; -- diabetic eye exam
-- modest default for any remaining active measures
UPDATE phm_edw.measure_definition SET net_revenue = 25.00 WHERE net_revenue IS NULL AND active_ind = 'Y';

-- ─── Uncontrolled thresholds (rules engine) — MTM auto-referral triggers ─────
INSERT INTO phm_edw.clinical_rule (entity, attribute, value_jsonb, display_order, source) VALUES
  ('UNCONTROLLED_THRESHOLD', 'RULE', '{"condition":"diabetes","code":"4548-4","op":">=","value":9.0,"unit":"%"}'::jsonb,     1, 'ADA 2024 (poor control >9%)'),
  ('UNCONTROLLED_THRESHOLD', 'RULE', '{"condition":"hypertension","code":"SBP","op":">=","value":140,"unit":"mmHg"}'::jsonb, 2, 'ACC/AHA 2017'),
  ('UNCONTROLLED_THRESHOLD', 'RULE', '{"condition":"hyperlipidemia","code":"18262-6","op":">=","value":100,"unit":"mg/dL"}'::jsonb, 3, 'Hyperlipidemia LDL goal <100');

-- ─── Chronic-monitoring auto-order protocol ──────────────────────────────────
INSERT INTO phm_edw.order_protocol (protocol_code, protocol_name, description)
VALUES ('CHRONIC_MONITORING', 'Chronic Disease Monitoring Labs',
        'Standing labs for chronic-disease management — generated by protocol, co-signed once.')
ON CONFLICT (protocol_code) DO NOTHING;

-- Link recurring lab items by LOINC (one item per code); skips codes with no item.
INSERT INTO phm_edw.order_protocol_item (protocol_id, item_id, interval_days)
SELECT pr.protocol_id, picks.item_id, picks.interval_days
FROM phm_edw.order_protocol pr
CROSS JOIN LATERAL (
  SELECT item_id, interval_days FROM (
    SELECT (SELECT item_id FROM phm_edw.order_set_item WHERE loinc_code = '4548-4'  AND active_ind='Y' ORDER BY item_id LIMIT 1) AS item_id, 180 AS interval_days
    UNION ALL
    SELECT (SELECT item_id FROM phm_edw.order_set_item WHERE loinc_code = '24331-1' AND active_ind='Y' ORDER BY item_id LIMIT 1), 365
    UNION ALL
    SELECT (SELECT item_id FROM phm_edw.order_set_item WHERE loinc_code = '9318-7'  AND active_ind='Y' ORDER BY item_id LIMIT 1), 365
    UNION ALL
    SELECT (SELECT item_id FROM phm_edw.order_set_item WHERE loinc_code = '51990-0' AND active_ind='Y' ORDER BY item_id LIMIT 1), 365
  ) x WHERE item_id IS NOT NULL
) picks
WHERE pr.protocol_code = 'CHRONIC_MONITORING'
ON CONFLICT (protocol_id, item_id) DO NOTHING;
